# syntax=docker/dockerfile:1

# Builder stage
FROM ghcr.io/trueforge-org/python:3.13.7 AS builder
ARG VERSION

USER root
WORKDIR /tmp

# Install dependencies, download, and build Theme.Park
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        sed \
    && rm -rf /var/lib/apt/lists/*; \
    \
    curl -fsSL "https://github.com/themepark-dev/theme.park/archive/${VERSION}.tar.gz" \
        | tar xzf - --strip-components=1; \
    python3 themes.py; \
    grep -rl 'https://theme-park.dev' . | xargs sed -i 's|https\://theme-park.dev||g'

# Nginx stage
FROM nginx:1.27
ENV NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE=1

# Copy built files from builder
COPY --from=builder --chown=www-data:www-data /tmp/index.html /usr/share/nginx/html/
COPY --from=builder --chown=www-data:www-data /tmp/css /usr/share/nginx/html/css/
COPY --from=builder --chown=www-data:www-data /tmp/resources /usr/share/nginx/html/resources/

USER www-data
WORKDIR /usr/share/nginx/html
